# Generated by Django 4.1.5 on 2023-03-19 20:06

from django.db import migrations


class Migration(migrations.Migration):
    def create_statuses(apps, schema_editor):
        TaskStatus = apps.get_model('api', 'TaskStatus')
        TaskStatus.objects.create(name="new")
        TaskStatus.objects.create(name="in work")
        TaskStatus.objects.create(name="done")

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(create_statuses)
    ]
